"""``notifications`` repository (BACKEND_ARCHITECTURE.md §12; DATABASE_DESIGN.md §19).

Workflow & Support: user-facing activity feed and toasts — unread listing and
counts for the dashboard, plus read marking. Notifications are generated by
workflow events, never ad hoc.
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence

from sqlalchemy.sql.base import ExecutableOption

from app.models import Notification
from app.repositories.base import BaseRepository
from app.utils.time import utc_now


class NotificationRepository(BaseRepository[Notification]):
    """Data access for :class:`app.models.notifications.Notification`."""

    model = Notification

    async def list_unread(
        self,
        user_id: uuid.UUID,
        *,
        options: Sequence[ExecutableOption] = (),
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[Notification]:
        """List a user's live, unread notifications, newest first."""
        return await self.list(
            Notification.user_id == user_id,
            Notification.read_at.is_(None),
            order_by=[Notification.created_at.desc()],
            options=options,
            limit=limit,
            offset=offset,
        )

    async def count_unread(self, user_id: uuid.UUID) -> int:
        """Count a user's live, unread notifications."""
        return await self.count(
            Notification.user_id == user_id,
            Notification.read_at.is_(None),
        )

    async def mark_read(self, notification: Notification) -> Notification:
        """Mark a notification read now."""
        return await self.update(notification, read_at=utc_now())


__all__ = ["NotificationRepository"]
