"""``notifications`` model (DATABASE_DESIGN.md §19).

Workflow & Support: user-facing activity feed and toasts. Notifications are
generated by workflow events, never ad hoc. Priority model matches
ui-ux-design.md §18.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any

import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.models.enums import (
    NOTIFICATION_PRIORITY,
    NOTIFICATION_TYPE,
    NotificationPriority,
    NotificationType,
)
from app.models.mixins import CreatedAtMixin, SoftDeleteMixin, UUIDPrimaryKeyMixin
from app.models.types import JsonB

if TYPE_CHECKING:
    from app.models.requests import Request
    from app.models.users import User


class Notification(UUIDPrimaryKeyMixin, CreatedAtMixin, SoftDeleteMixin, Base):
    """User-facing activity notification (DATABASE_DESIGN.md §19)."""

    __tablename__ = "notifications"

    user_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid(as_uuid=True),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    request_id: Mapped[uuid.UUID | None] = mapped_column(
        sa.Uuid(as_uuid=True),
        sa.ForeignKey("requests.id", ondelete="SET NULL"),
        nullable=True,
    )
    type: Mapped[NotificationType] = mapped_column(NOTIFICATION_TYPE, nullable=False)
    priority: Mapped[NotificationPriority] = mapped_column(
        NOTIFICATION_PRIORITY, nullable=False, server_default=sa.text("'medium'")
    )
    title: Mapped[str] = mapped_column(sa.String(200), nullable=False)
    body: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    link: Mapped[str | None] = mapped_column(sa.String(500), nullable=True)
    icon: Mapped[str | None] = mapped_column(sa.String(50), nullable=True)
    read_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )
    delivered_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )
    metadata_: Mapped[dict[str, Any] | None] = mapped_column(
        "metadata", JsonB, nullable=True, server_default=sa.text("'{}'")
    )

    __table_args__ = (
        sa.Index("ix_notifications_user_id_read_at", "user_id", "read_at"),
        sa.Index(
            "ix_notifications_unread_partial",
            "user_id",
            postgresql_where=sa.text("read_at IS NULL AND deleted_at IS NULL"),
            sqlite_where=sa.text("read_at IS NULL AND deleted_at IS NULL"),
        ),
    )

    user: Mapped[User] = relationship(foreign_keys=[user_id], overlaps="notifications")
    request: Mapped[Request | None] = relationship(
        foreign_keys=[request_id], overlaps="notifications"
    )
