"""``notifications`` service (BACKEND_ARCHITECTURE.md §11; DATABASE_DESIGN.md §19).

Workflow & Support: user-facing activity feed and toasts. Notifications are
generated by workflow events, never ad hoc (BACKEND_ARCHITECTURE.md §32.5);
the service owns creation and read-marking only.
"""

from __future__ import annotations

import uuid
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Notification, NotificationPriority, NotificationType
from app.repositories import (
    NotificationRepository,
    Page,
    RequestRepository,
    UserRepository,
)
from app.services.base import BaseService
from app.services.exceptions import InvalidStateError, NotFoundError, ValidationError


class NotificationService(BaseService):
    """Notification operations for :class:`app.models.notifications.Notification`."""

    def __init__(
        self,
        session: AsyncSession,
        notifications: NotificationRepository | None = None,
        users: UserRepository | None = None,
        requests: RequestRepository | None = None,
    ) -> None:
        super().__init__(session)
        self._notifications = notifications or NotificationRepository(session)
        self._users = users or UserRepository(session)
        self._requests = requests or RequestRepository(session)

    async def create_notification(
        self,
        *,
        user_id: uuid.UUID,
        type: NotificationType,
        title: str,
        body: str | None = None,
        link: str | None = None,
        icon: str | None = None,
        priority: NotificationPriority = NotificationPriority.MEDIUM,
        request_id: uuid.UUID | None = None,
        metadata_: dict[str, Any] | None = None,
    ) -> Notification:
        """Create an in-app notification for a user."""
        if await self._users.get_by_id(user_id) is None:
            raise NotFoundError(message="User not found")
        if (
            request_id is not None
            and await self._requests.get_by_id(request_id) is None
        ):
            raise NotFoundError(message="Request not found")
        type = self._validate_enum(type, NotificationType, field="type")
        priority = self._validate_enum(
            priority, NotificationPriority, field="priority"
        )
        title = self._validate_not_blank(title, field="title")
        if link is not None and len(link) > 500:
            raise ValidationError(
                message="link must be at most 500 characters",
                details=[{"field": "link", "reason": "too long"}],
            )
        values: dict[str, Any] = {
            "user_id": user_id,
            "request_id": request_id,
            "type": type,
            "priority": priority,
            "title": title,
            "body": body,
            "link": link,
            "icon": icon,
        }
        if metadata_ is not None:
            values["metadata_"] = metadata_
        return await self._notifications.create(**values)

    async def mark_read(self, *, notification_id: uuid.UUID) -> Notification:
        """Mark one notification as read; raises when already read."""
        notification = await self._require_notification(notification_id)
        if notification.read_at is not None:
            raise InvalidStateError(message="Notification is already read")
        return await self._notifications.mark_read(notification)

    async def mark_all_read(self, *, user_id: uuid.UUID) -> int:
        """Mark every unread notification of a user as read; returns the count."""
        if await self._users.get_by_id(user_id) is None:
            raise NotFoundError(message="User not found")
        unread = await self._notifications.list_unread(user_id)
        for notification in unread:
            await self._notifications.mark_read(notification)
        return len(unread)

    async def list_user_notifications(
        self,
        *,
        user_id: uuid.UUID,
        page: int = 1,
        limit: int = 20,
        read: bool | None = None,
    ) -> Page[Notification]:
        """Paginate a user's notifications, optionally filtered by read state."""
        if await self._users.get_by_id(user_id) is None:
            raise NotFoundError(message="User not found")
        filters = [Notification.user_id == user_id]
        if read is True:
            filters.append(Notification.read_at.isnot(None))
        elif read is False:
            filters.append(Notification.read_at.is_(None))
        return await self._notifications.paginate(
            page=page,
            limit=limit,
            filters=filters,
            order_by=[Notification.created_at.desc()],
        )

    async def count_unread(self, *, user_id: uuid.UUID) -> int:
        """Count a user's live, unread notifications."""
        if await self._users.get_by_id(user_id) is None:
            raise NotFoundError(message="User not found")
        return await self._notifications.count_unread(user_id)

    async def delete_notification(
        self, *, notification_id: uuid.UUID
    ) -> Notification:
        """Soft-delete a notification (DATABASE_DESIGN.md §26)."""
        notification = await self._require_notification(notification_id)
        return await self._notifications.soft_delete(notification)

    async def _require_notification(
        self, notification_id: uuid.UUID
    ) -> Notification:
        notification = await self._notifications.get_by_id(notification_id)
        if notification is None:
            raise NotFoundError(message="Notification not found")
        return notification
