"""Notification endpoints (API_SPECIFICATION.md §19).

Purpose:
    Owner-scoped activity feed: listing, read-marking, unread counts, and
    soft-delete. Notifications are generated by workflow events, never ad hoc
    (BACKEND_ARCHITECTURE.md §32.5).
"""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, Request

from app.dependencies.auth import CurrentUser, get_current_user
from app.dependencies.services import (
    get_notification_repository,
    get_notification_service,
)
from app.exceptions.app_error import ForbiddenError
from app.models import Notification
from app.repositories import NotificationRepository
from app.schemas.notifications import NotificationRead, UnreadCountRead
from app.schemas.response import SuccessResponse
from app.services import NotificationService
from app.services.exceptions import NotFoundError
from app.utils.response import pagination_meta, success_response

router = APIRouter(prefix="/notifications", tags=["notifications"])


async def _require_owned_notification(
    notification_id: uuid.UUID,
    user_id: uuid.UUID,
    notifications: NotificationRepository,
) -> Notification:
    """Fetch a notification and assert the acting user owns it."""
    notification = await notifications.get_by_id(notification_id)
    if notification is None:
        raise NotFoundError(message="Notification not found")
    if notification.user_id != user_id:
        raise ForbiddenError(message="You do not own this notification")
    return notification


@router.get(
    "",
    response_model=SuccessResponse[list[NotificationRead]],
    summary="List own notifications",
)
async def list_notifications(
    request: Request,
    page: int = 1,
    limit: int = 20,
    read: bool | None = None,
    current_user: CurrentUser = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
) -> SuccessResponse[list[NotificationRead]]:
    """Paginate the acting user's notifications, optionally filtered by read (§19)."""
    page_result = await service.list_user_notifications(
        user_id=current_user.user_id, page=page, limit=limit, read=read
    )
    return success_response(
        request,
        [NotificationRead.model_validate(item) for item in page_result.items],
        pagination=pagination_meta(page_result),
    )


@router.get(
    "/unread-count",
    response_model=SuccessResponse[UnreadCountRead],
    summary="Count unread notifications",
)
async def unread_count(
    request: Request,
    current_user: CurrentUser = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
) -> SuccessResponse[UnreadCountRead]:
    """Return the acting user's unread notification count (§19)."""
    count = await service.count_unread(user_id=current_user.user_id)
    return success_response(request, UnreadCountRead(unread=count))


@router.post(
    "/read-all",
    response_model=SuccessResponse[dict[str, int]],
    summary="Mark all own notifications as read",
)
async def mark_all_read(
    request: Request,
    current_user: CurrentUser = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
) -> SuccessResponse[dict[str, int]]:
    """Mark every unread notification of the acting user as read (§19)."""
    marked = await service.mark_all_read(user_id=current_user.user_id)
    return success_response(request, {"marked": marked})


@router.post(
    "/{notification_id}/read",
    response_model=SuccessResponse[NotificationRead],
    summary="Mark one notification as read",
)
async def mark_read(
    notification_id: uuid.UUID,
    request: Request,
    current_user: CurrentUser = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
    notifications: NotificationRepository = Depends(get_notification_repository),
) -> SuccessResponse[NotificationRead]:
    """Mark an owned notification as read (§19)."""
    await _require_owned_notification(
        notification_id, current_user.user_id, notifications
    )
    notification = await service.mark_read(notification_id=notification_id)
    return success_response(request, NotificationRead.model_validate(notification))


@router.delete(
    "/{notification_id}",
    response_model=SuccessResponse[NotificationRead],
    summary="Soft-delete a notification",
)
async def delete_notification(
    notification_id: uuid.UUID,
    request: Request,
    current_user: CurrentUser = Depends(get_current_user),
    service: NotificationService = Depends(get_notification_service),
    notifications: NotificationRepository = Depends(get_notification_repository),
) -> SuccessResponse[NotificationRead]:
    """Soft-delete an owned notification (§19; DATABASE_DESIGN.md §26)."""
    await _require_owned_notification(
        notification_id, current_user.user_id, notifications
    )
    notification = await service.delete_notification(
        notification_id=notification_id
    )
    return success_response(request, NotificationRead.model_validate(notification))
